package com.etecsa.domain;

import static com.etecsa.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class AlarmaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlarmaAllPropertiesEquals(Alarma expected, Alarma actual) {
        assertAlarmaAutoGeneratedPropertiesEquals(expected, actual);
        assertAlarmaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlarmaAllUpdatablePropertiesEquals(Alarma expected, Alarma actual) {
        assertAlarmaUpdatableFieldsEquals(expected, actual);
        assertAlarmaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlarmaAutoGeneratedPropertiesEquals(Alarma expected, Alarma actual) {
        assertThat(actual)
            .as("Verify Alarma auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlarmaUpdatableFieldsEquals(Alarma expected, Alarma actual) {
        assertThat(actual)
            .as("Verify Alarma relevant properties")
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a ->
                assertThat(a.getActivatedAt())
                    .as("check activatedAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getActivatedAt())
            )
            .satisfies(a ->
                assertThat(a.getDeactivatedAt())
                    .as("check deactivatedAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getDeactivatedAt())
            )
            .satisfies(a -> assertThat(a.getSeveridad()).as("check severidad").isEqualTo(expected.getSeveridad()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getMensajeUsuario()).as("check mensajeUsuario").isEqualTo(expected.getMensajeUsuario()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlarmaUpdatableRelationshipsEquals(Alarma expected, Alarma actual) {
        assertThat(actual)
            .as("Verify Alarma relationships")
            .satisfies(a -> assertThat(a.getEvento()).as("check evento").isEqualTo(expected.getEvento()));
    }
}
