package com.etecsa.domain;

import static com.etecsa.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class EquipoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipoAllPropertiesEquals(Equipo expected, Equipo actual) {
        assertEquipoAutoGeneratedPropertiesEquals(expected, actual);
        assertEquipoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipoAllUpdatablePropertiesEquals(Equipo expected, Equipo actual) {
        assertEquipoUpdatableFieldsEquals(expected, actual);
        assertEquipoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipoAutoGeneratedPropertiesEquals(Equipo expected, Equipo actual) {
        assertThat(actual)
            .as("Verify Equipo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipoUpdatableFieldsEquals(Equipo expected, Equipo actual) {
        assertThat(actual)
            .as("Verify Equipo relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDireccionIp()).as("check direccionIp").isEqualTo(expected.getDireccionIp()))
            .satisfies(a -> assertThat(a.getModbusSlaveId()).as("check modbusSlaveId").isEqualTo(expected.getModbusSlaveId()))
            .satisfies(a -> assertThat(a.getModelo()).as("check modelo").isEqualTo(expected.getModelo()))
            .satisfies(a -> assertThat(a.getFirmwareVersion()).as("check firmwareVersion").isEqualTo(expected.getFirmwareVersion()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a ->
                assertThat(a.getUltimoHeartbeat())
                    .as("check ultimoHeartbeat")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getUltimoHeartbeat())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEquipoUpdatableRelationshipsEquals(Equipo expected, Equipo actual) {
        assertThat(actual)
            .as("Verify Equipo relationships")
            .satisfies(a -> assertThat(a.getSitio()).as("check sitio").isEqualTo(expected.getSitio()))
            .satisfies(a -> assertThat(a.getEspecialidades()).as("check especialidades").isEqualTo(expected.getEspecialidades()));
    }
}
