package com.etecsa.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EventoPlantillaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoPlantillaAllPropertiesEquals(EventoPlantilla expected, EventoPlantilla actual) {
        assertEventoPlantillaAutoGeneratedPropertiesEquals(expected, actual);
        assertEventoPlantillaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoPlantillaAllUpdatablePropertiesEquals(EventoPlantilla expected, EventoPlantilla actual) {
        assertEventoPlantillaUpdatableFieldsEquals(expected, actual);
        assertEventoPlantillaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoPlantillaAutoGeneratedPropertiesEquals(EventoPlantilla expected, EventoPlantilla actual) {
        assertThat(actual)
            .as("Verify EventoPlantilla auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoPlantillaUpdatableFieldsEquals(EventoPlantilla expected, EventoPlantilla actual) {
        assertThat(actual)
            .as("Verify EventoPlantilla relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getScalingFactor()).as("check scalingFactor").isEqualTo(expected.getScalingFactor()))
            .satisfies(a -> assertThat(a.getUnidadMedida()).as("check unidadMedida").isEqualTo(expected.getUnidadMedida()))
            .satisfies(a -> assertThat(a.getFuncionLectura()).as("check funcionLectura").isEqualTo(expected.getFuncionLectura()))
            .satisfies(a -> assertThat(a.getFuncionEscritura()).as("check funcionEscritura").isEqualTo(expected.getFuncionEscritura()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoPlantillaUpdatableRelationshipsEquals(EventoPlantilla expected, EventoPlantilla actual) {
        assertThat(actual)
            .as("Verify EventoPlantilla relationships")
            .satisfies(a -> assertThat(a.getEspecialidad()).as("check especialidad").isEqualTo(expected.getEspecialidad()));
    }
}
