package com.etecsa.domain;

import static com.etecsa.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class EventoEquipoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoEquipoAllPropertiesEquals(EventoEquipo expected, EventoEquipo actual) {
        assertEventoEquipoAutoGeneratedPropertiesEquals(expected, actual);
        assertEventoEquipoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoEquipoAllUpdatablePropertiesEquals(EventoEquipo expected, EventoEquipo actual) {
        assertEventoEquipoUpdatableFieldsEquals(expected, actual);
        assertEventoEquipoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoEquipoAutoGeneratedPropertiesEquals(EventoEquipo expected, EventoEquipo actual) {
        assertThat(actual)
            .as("Verify EventoEquipo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoEquipoUpdatableFieldsEquals(EventoEquipo expected, EventoEquipo actual) {
        assertThat(actual)
            .as("Verify EventoEquipo relevant properties")
            .satisfies(a -> assertThat(a.getNombreVariable()).as("check nombreVariable").isEqualTo(expected.getNombreVariable()))
            .satisfies(a -> assertThat(a.getDireccionModbus()).as("check direccionModbus").isEqualTo(expected.getDireccionModbus()))
            .satisfies(a -> assertThat(a.getTipoRegistro()).as("check tipoRegistro").isEqualTo(expected.getTipoRegistro()))
            .satisfies(a -> assertThat(a.getTipoDato()).as("check tipoDato").isEqualTo(expected.getTipoDato()))
            .satisfies(a -> assertThat(a.getEsEscribible()).as("check esEscribible").isEqualTo(expected.getEsEscribible()))
            .satisfies(a -> assertThat(a.getValorNumerico()).as("check valorNumerico").isEqualTo(expected.getValorNumerico()))
            .satisfies(a -> assertThat(a.getValorBooleano()).as("check valorBooleano").isEqualTo(expected.getValorBooleano()))
            .satisfies(a ->
                assertThat(a.getTimestampActualizacion())
                    .as("check timestampActualizacion")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getTimestampActualizacion())
            )
            .satisfies(a -> assertThat(a.getIntervaloLectura()).as("check intervaloLectura").isEqualTo(expected.getIntervaloLectura()))
            .satisfies(a -> assertThat(a.getUmbralAlerta()).as("check umbralAlerta").isEqualTo(expected.getUmbralAlerta()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoEquipoUpdatableRelationshipsEquals(EventoEquipo expected, EventoEquipo actual) {
        assertThat(actual)
            .as("Verify EventoEquipo relationships")
            .satisfies(a -> assertThat(a.getEquipo()).as("check equipo").isEqualTo(expected.getEquipo()))
            .satisfies(a -> assertThat(a.getPlantilla()).as("check plantilla").isEqualTo(expected.getPlantilla()));
    }
}
