package com.etecsa.domain;

import static com.etecsa.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class SitioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSitioAllPropertiesEquals(Sitio expected, Sitio actual) {
        assertSitioAutoGeneratedPropertiesEquals(expected, actual);
        assertSitioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSitioAllUpdatablePropertiesEquals(Sitio expected, Sitio actual) {
        assertSitioUpdatableFieldsEquals(expected, actual);
        assertSitioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSitioAutoGeneratedPropertiesEquals(Sitio expected, Sitio actual) {
        assertThat(actual)
            .as("Verify Sitio auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSitioUpdatableFieldsEquals(Sitio expected, Sitio actual) {
        assertThat(actual)
            .as("Verify Sitio relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getCodigo()).as("check codigo").isEqualTo(expected.getCodigo()))
            .satisfies(a -> assertThat(a.getUbicacion()).as("check ubicacion").isEqualTo(expected.getUbicacion()))
            .satisfies(a ->
                assertThat(a.getFechaRegistro())
                    .as("check fechaRegistro")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getFechaRegistro())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSitioUpdatableRelationshipsEquals(Sitio expected, Sitio actual) {
        // empty method
    }
}
